### ISSUE TITLE
Suggestion: Add Second Chances and Airs of London to the bar.

### ISSUE THREAD

**Issue by Maddremor** [Laurvin/Fallen-London-Contacts-Favours#2]
As a purely selfish suggestion, could adding Second Chances and Airs of London to the bar alongside the favors or some other convenient nook in the page be reasonable?

**Comment by Laurvin** [comment]
Sorry for not replying earlier; for some reasons I didn't get notifications by default.

I've fixed the script so that it now fires even after changing to other tabs. It checks every 20 seconds and reloads itself if it's gone.

Airs of London unfortunately don't show up in the api call; it's something I would really like to show up as well.

Second Chances would be possible but is there any reason when you can hover over the icon and see the amount on any test where they are used?
